# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Payze-Demo-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Payze-Demo-App
    
    pod 'Payze-iOS-sdk', :path => "../"
    
end
